#!/usr/bin/env bash

set -e # Exit on errors

if [ ! -x /usr/sbin/sshd ]; then
  echo "-> Installing SSH Server..."
  yum -y install openssh-server
  chkconfig sshd off
  echo "-> Configuring SSH Server..."
  sed -i "s/#PermitRootLogin.*/PermitRootLogin yes/g" /etc/ssh/sshd_config
  sed -i "s/#UsePrivilegeSeparation.*/UsePrivilegeSeparation no/g" /etc/ssh/sshd_config
  sed -i "s/UsePAM.*/UsePAM no/g" /etc/ssh/sshd_config
  echo "-> Generating SSH Server Keys..."
  ssh-keygen -q -N "" -t rsa1 -f /etc/ssh/ssh_host_key
  ssh-keygen -q -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key
  ssh-keygen -q -N "" -t dsa -f /etc/ssh/ssh_host_dsa_key
fi

echo "-> Starting SSH Server..."
/usr/sbin/sshd -D -e &

# Kill sshd process on signals from supervisor
trap 'kill $(jobs -p)' SIGINT SIGTERM EXIT

# Wait for sshd process to terminate
wait $(jobs -p)